user_validates:
  password_min_length: 6
  email_max_length: 255
  name_max_length: 50
micropost:
  content_max_length: 140
  max_size_image: 5
user_helpper:
  size: 80
string_one: "1"
avt_size: 50
user_number: 15
micropost_number: 20
resize_to_limit: [250, 250]
feed_number: 15
follow_number: 10
time_reset: 2
